In [51]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [52]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [53]:
with open('gender_label_encoder.pkl','rb') as file:
    gender_label_encoder=pickle.load(file)

with open('geography_oh_encoder.pkl','rb') as file:
    geography_oh_encoder=pickle.load(file)
   
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [54]:
# example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [55]:
input_data=pd.DataFrame([input_data])

In [56]:
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [ ]:
input_data['Gender']=gender_label_encoder.transform(input_data['Gender'])

In [60]:
input_data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [63]:
geo_transformed=geography_oh_encoder.transform(input_data[['Geography']]).toarray()
feature_name=geography_oh_encoder.get_feature_names_out(['Geography'])
geo_df=pd.DataFrame(geo_transformed,columns=feature_name)

In [65]:
input_df=pd.concat([input_data.drop(['Geography'],axis=1),geo_df],axis=1)

In [66]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [68]:
input_scaled=scaler.transform(input_df)

In [69]:
prediction=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 633ms/step

In [70]:
prediction_proba = prediction[0][0]

In [71]:
prediction_proba

0.024073059